// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Information.proto

package com.xzh.netty.queuetask;

public final class InformationProto {
  private InformationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Information)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes header = 1;</code>
     * @return The header.
     */
    com.google.protobuf.ByteString getHeader();

    /**
     * <code>bytes msgtype = 2;</code>
     * @return The msgtype.
     */
    com.google.protobuf.ByteString getMsgtype();

    /**
     * <code>fixed32 personnum = 3;</code>
     * @return The personnum.
     */
    int getPersonnum();

    /**
     * <code>float price = 4;</code>
     * @return The price.
     */
    float getPrice();

    /**
     * <code>string content = 5;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code Information}
   */
  public static final class Information extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Information)
      InformationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Information.newBuilder() to construct.
    private Information(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Information() {
      header_ = com.google.protobuf.ByteString.EMPTY;
      msgtype_ = com.google.protobuf.ByteString.EMPTY;
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Information();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Information(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              header_ = input.readBytes();
              break;
            }
            case 18: {

              msgtype_ = input.readBytes();
              break;
            }
            case 29: {

              personnum_ = input.readFixed32();
              break;
            }
            case 37: {

              price_ = input.readFloat();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InformationProto.internal_static_Information_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InformationProto.internal_static_Information_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Information.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString header_;
    /**
     * <code>bytes header = 1;</code>
     * @return The header.
     */
    @Override
    public com.google.protobuf.ByteString getHeader() {
      return header_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgtype_;
    /**
     * <code>bytes msgtype = 2;</code>
     * @return The msgtype.
     */
    @Override
    public com.google.protobuf.ByteString getMsgtype() {
      return msgtype_;
    }

    public static final int PERSONNUM_FIELD_NUMBER = 3;
    private int personnum_;
    /**
     * <code>fixed32 personnum = 3;</code>
     * @return The personnum.
     */
    @Override
    public int getPersonnum() {
      return personnum_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>float price = 4;</code>
     * @return The price.
     */
    @Override
    public float getPrice() {
      return price_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile Object content_;
    /**
     * <code>string content = 5;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!header_.isEmpty()) {
        output.writeBytes(1, header_);
      }
      if (!msgtype_.isEmpty()) {
        output.writeBytes(2, msgtype_);
      }
      if (personnum_ != 0) {
        output.writeFixed32(3, personnum_);
      }
      if (price_ != 0F) {
        output.writeFloat(4, price_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!header_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, header_);
      }
      if (!msgtype_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msgtype_);
      }
      if (personnum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, personnum_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Information)) {
        return super.equals(obj);
      }
      Information other = (Information) obj;

      if (!getHeader()
          .equals(other.getHeader())) return false;
      if (!getMsgtype()
          .equals(other.getMsgtype())) return false;
      if (getPersonnum()
          != other.getPersonnum()) return false;
      if (Float.floatToIntBits(getPrice())
          != Float.floatToIntBits(
              other.getPrice())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgtype().hashCode();
      hash = (37 * hash) + PERSONNUM_FIELD_NUMBER;
      hash = (53 * hash) + getPersonnum();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPrice());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Information parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Information parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Information parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Information parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Information parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Information parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Information parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Information parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Information parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Information parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Information parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Information parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Information prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Information}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Information)
        InformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InformationProto.internal_static_Information_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InformationProto.internal_static_Information_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Information.class, Builder.class);
      }

      // Construct using com.xzh.netty.protobuf.InformationProto.Information.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        header_ = com.google.protobuf.ByteString.EMPTY;

        msgtype_ = com.google.protobuf.ByteString.EMPTY;

        personnum_ = 0;

        price_ = 0F;

        content_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InformationProto.internal_static_Information_descriptor;
      }

      @Override
      public Information getDefaultInstanceForType() {
        return Information.getDefaultInstance();
      }

      @Override
      public Information build() {
        Information result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Information buildPartial() {
        Information result = new Information(this);
        result.header_ = header_;
        result.msgtype_ = msgtype_;
        result.personnum_ = personnum_;
        result.price_ = price_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Information) {
          return mergeFrom((Information)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Information other) {
        if (other == Information.getDefaultInstance()) return this;
        if (other.getHeader() != com.google.protobuf.ByteString.EMPTY) {
          setHeader(other.getHeader());
        }
        if (other.getMsgtype() != com.google.protobuf.ByteString.EMPTY) {
          setMsgtype(other.getMsgtype());
        }
        if (other.getPersonnum() != 0) {
          setPersonnum(other.getPersonnum());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Information parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Information) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString header_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes header = 1;</code>
       * @return The header.
       */
      @Override
      public com.google.protobuf.ByteString getHeader() {
        return header_;
      }
      /**
       * <code>bytes header = 1;</code>
       * @param value The header to set.
       * @return This builder for chaining.
       */
      public Builder setHeader(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        header_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes header = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeader() {
        
        header_ = getDefaultInstance().getHeader();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgtype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msgtype = 2;</code>
       * @return The msgtype.
       */
      @Override
      public com.google.protobuf.ByteString getMsgtype() {
        return msgtype_;
      }
      /**
       * <code>bytes msgtype = 2;</code>
       * @param value The msgtype to set.
       * @return This builder for chaining.
       */
      public Builder setMsgtype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msgtype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgtype() {
        
        msgtype_ = getDefaultInstance().getMsgtype();
        onChanged();
        return this;
      }

      private int personnum_ ;
      /**
       * <code>fixed32 personnum = 3;</code>
       * @return The personnum.
       */
      @Override
      public int getPersonnum() {
        return personnum_;
      }
      /**
       * <code>fixed32 personnum = 3;</code>
       * @param value The personnum to set.
       * @return This builder for chaining.
       */
      public Builder setPersonnum(int value) {
        
        personnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 personnum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersonnum() {
        
        personnum_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 4;</code>
       * @return The price.
       */
      @Override
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 5;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Information)
    }

    // @@protoc_insertion_point(class_scope:Information)
    private static final Information DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Information();
    }

    public static Information getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Information>
        PARSER = new com.google.protobuf.AbstractParser<Information>() {
      @Override
      public Information parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Information(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Information> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Information> getParserForType() {
      return PARSER;
    }

    @Override
    public Information getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Information_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Information_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021Information.proto\"a\n\013Information\022\016\n\006he" +
      "ader\030\001 \001(\014\022\017\n\007msgtype\030\002 \001(\014\022\021\n\tpersonnum" +
      "\030\003 \001(\007\022\r\n\005price\030\004 \001(\002\022\017\n\007content\030\005 \001(\tB*" +
      "\n\026com.xzh.netty.protobufB\020InformationPro" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Information_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Information_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Information_descriptor,
        new String[] { "Header", "Msgtype", "Personnum", "Price", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
